### ISSUE TITLE
pls. remove mediacrush

### ISSUE THREAD

**Issue by agaida** [QtDesktop/screengrab#16]
because uploads are no longer possible:  http://mediacrush.net/

**Comment by jleclanche** [comment]
The central mediacru.sh server should be removed, but uploads to mediacrush instances is still possible as it's open source and self-hostable.

**Comment by jleclanche** [comment]
We should add a way of specifying a preferred mediacrush server.

**Comment by agaida** [comment]
sounds good

**Comment by DOOMer** [comment]
Well, I'm can make  additional settings for customize url for uploading screenshots to self-hosted mediacru.sh. If it's need for community.

**Comment by paulolieuthier** [comment]
@DOOMer we should do that. Or remove it completely. One way or another, imgur should be the default option now.

**Comment by jleclanche** [comment]
Yep.

**Comment by jleclanche** [comment]
Let's keep the mediacrush option though, imgur is not open source unlike mediacrush.

**Comment by DOOMer** [comment]
> Let's keep the mediacrush option though, imgur is not open source unlike mediacrush.

Implemented in 5ea99fec971abbba3feabcf4f2a39eee1b97233c

**Comment by agaida** [comment]
Thank you very much
