### ISSUE TITLE
Upload: data of Imgur and MediaCrush swapped

### ISSUE THREAD

**Issue by pmattern** [QtDesktop/screengrab#26]
The data of Imgur and MediaCrush are swapped both in dialog "Options"
![screengrab_upload-url_dialog-options](https://cloud.githubusercontent.com/assets/9860801/12011462/3fe1014e-acce-11e5-9f4e-95aa951627a3.png)
and "Upload to the internet".
![screengrab_upload-url_dialog-upload](https://cloud.githubusercontent.com/assets/9860801/12011463/460e191c-acce-11e5-8561-54ca1db6fc5d.png)
Same findings the other way around in both dialogs when "MediaCrush" gets selected instead of "Imgur".
As a consequence choosing "Imgur" fails as an attempt is made to reach the no longer existing main MediaCrush server while selecting "MediaCrush" triggers a flawless upload to Imgur.

3b687f6, Arch Linux, user account where ScreenGrab hadn't been used before.

Note:
If PR #22 gets accepted it would make sense to merge before addressing this issue as probably some files are covered by both.

**Comment by jleclanche** [comment]
@pmattern i meant to address that... it's my bad. do you want to fix it in your pr?

**Comment by pmattern** [comment]
> do you want to fix it in your pr?

Hate to say but I'm lacking the skills. So no...

**Comment by jleclanche** [comment]
I think it's just an issue with ordering of imgur and mediacrush classes in the upload class.
